### ISSUE TITLE
ERROR: Writing the FPGA configuration failed

### ISSUE THREAD

**Issue by filip-dahlberg** [robseb/LinuxVSCppFPGA#1]
First off, I really appreciate all work in this repo.

I'm experiencing problem to read/write data on light-weight bridge with HPS while in SSH. 

My hardware set-up is DE0 Atlas Nano version C (Cyclone V). My MSEL are set to:
  
![image](https://user-images.githubusercontent.com/37364201/92458053-406da400-f1c5-11ea-8ae4-e1ec1b78ccd4.png)

The console output when trying to write the original FPGA binary file is as follows:
![image](https://user-images.githubusercontent.com/37364201/92458208-6004cc80-f1c5-11ea-9b5c-8a41613afbb6.png)

Some more info:
When executing a FPGA-readBridge, it times out and the watchdog timer in triggers a reboot of Linux.
![image](https://user-images.githubusercontent.com/37364201/92458813-326c5300-f1c6-11ea-9300-08d17c33850c.png)

Can anyone help me with providing some input on how I'll establish working FPGA-writeBrdge and FPGA-readBridge commands from the HPS.

**Comment by robseb** [comment]
I think you are using rsyocto 1.031. 
Yesterday, I uploaded the version 1.041.  That is my first Version with the DE0 Nano SoC Kit support. With this version should it work. Here was the FPGA configuration writen for a diffrent board.
Note: please use the rs yocto github repository for r yocto issues. Thank you.

Robin

**Comment by filip-dahlberg** [comment]
Correct I'm not using 1.041, I'm using 1.032. I'll update to 1.041. Thank you so much!

**Comment by robseb** [comment]
no problem
